"""Build an explicit public-file allowlist. Does not upload or include raw conversations."""
from pathlib import Path
import argparse, hashlib, json, os, shutil

HERE = Path(__file__).resolve().parent
BASE = 'Qwen/Qwen3-4B-Instruct-2507'
REVISION = 'cdbee75f17c01a7cc42f958dc650907174af0554'

def sha(path):
    h=hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda:f.read(8*1024*1024),b''): h.update(chunk)
    return h.hexdigest()

def main():
    p=argparse.ArgumentParser()
    p.add_argument('--adapter',type=Path,required=True)
    p.add_argument('--gguf',type=Path,required=True)
    p.add_argument('--receipt',type=Path,required=True,help='Public aggregate release receipt; never raw responses')
    p.add_argument('--out',type=Path,required=True)
    a=p.parse_args()
    receipt=json.loads(a.receipt.read_text())
    required={'training','corpus','evaluation','limitations'}
    if not required <= receipt.keys(): raise ValueError(f'Receipt requires {sorted(required)}')
    if not a.gguf.is_file(): raise FileNotFoundError(a.gguf)
    if a.out.exists() and any(a.out.iterdir()): raise ValueError('Use an empty staging directory')
    a.out.mkdir(parents=True,exist_ok=True)
    def copy(src,dest,hardlink=False):
        dst=a.out/dest; dst.parent.mkdir(parents=True,exist_ok=True)
        if hardlink:
            try: os.link(src,dst); return
            except OSError: pass
        shutil.copyfile(src,dst)
    for name in ['adapter_config.json','adapter_model.safetensors']:
        copy(a.adapter/name,'adapter/'+name,hardlink=True)
    copy(a.gguf,'mem-extractor-q8_0.gguf',hardlink=True)
    copy(a.receipt,'release-receipt.json')
    copy(HERE/'reports/LICENSE-2.0.txt','LICENSE')
    for name in ['prompt.py','structured.py']:
        copy(HERE/name,'inference/'+name)
    for path in ['src/model/extract_schema.json','src/model/consolidate_schema.json','src/model/paired_sources.txt','src/worker/worker_system.txt','src/worker/extract_prompt.txt','src/worker/consolidate_prompt.txt','src/v2/reflect_prompt.txt']:
        copy(HERE.parent/path,path)
    for name in ['PROMPT_DESIGN.md','RESEARCH_PROTOCOL.md','EXTERNAL_LOCOMO.md']:
        copy(HERE/'reports'/name,'documentation/'+name)
    copy(HERE/'Finetuning_Iteration_Report.ipynb','documentation/Finetuning_Iteration_Report.ipynb')
    (a.out/'README.md').write_text(card(receipt))
    system=(HERE.parent/'src/worker/worker_system.txt').read_text().strip()
    template='{{- if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}<|im_start|>user\n{{ .Prompt }}<|im_end|>\n<|im_start|>assistant\n'
    (a.out/'Modelfile').write_text('FROM ./mem-extractor-q8_0.gguf\nTEMPLATE """'+template+'"""\nSYSTEM """'+system+'"""\nPARAMETER temperature 0\nPARAMETER num_ctx 12288\nPARAMETER stop "<|im_end|>"\nPARAMETER stop "<|endoftext|>"\n')
    copy(HERE/'release_inference.py','inference/run.py')
    files=sorted(p for p in a.out.rglob('*') if p.is_file())
    (a.out/'SHA256SUMS').write_text(''.join(f'{sha(f)}  {f.relative_to(a.out)}\n' for f in files))
    print(json.dumps({'directory':str(a.out),'files':len(files)+1,'bytes':sum(f.stat().st_size for f in files)},indent=2))

def card(r):
    return f'''---
license: apache-2.0
base_model: {BASE}
language:
- en
library_name: peft
tags:
- memory
- information-extraction
- qlora
- gguf
- synthetic-data
---
# mem-extractor

A fine-tuned 4B worker for **general-purpose conversational memory**: extracting evidence-backed facts, consolidating supported observations, and reflecting over retrieved evidence. Coding is one application, alongside personal preferences, relationships, plans, routines, learning, and work.

This release contains a PEFT adapter and merged Q8_0 GGUF. It is a research prototype, not an independently validated general-purpose memory benchmark winner. Use it with evidence validation and the supplied prompts/structured-output codec.

## Base and training

Base: [{BASE}](https://huggingface.co/{BASE}), pinned revision `{REVISION}` (Apache-2.0). Training uses Transformers/PEFT NF4 QLoRA with double quantization, bf16 compute, rank 16, alpha 32, dropout 0.05 and answer-only loss. Training targets are generated by GPT-5.6-sol through Pi: **sequence-level distillation**, not teacher-logit distillation. The release receipt records the actual final curriculum and hyperparameters.

```json
{json.dumps(r['training'],indent=2)}
```

## Corpus and provenance

```json
{json.dumps(r['corpus'],indent=2)}
```

General-purpose examples are synthetic and automatically audited. The inherited coding-stage adapter used a slice of [Nebius SWE-rebench OpenHands trajectories](https://huggingface.co/datasets/nebius/SWE-rebench-openhands-trajectories), CC-BY-4.0, plus synthetic examples; The warm-start lineage includes 118 relabeled public training windows before the stage-1 token filter; this data remains inherited even when later stages do not replay it. Multiple tasks from one scenario are correlated, so row counts are not independent conversation counts. No private user conversations or teacher credentials are included in this release.

[Hindsight is 20/20](https://arxiv.org/abs/2512.12818) and its [pinned extraction implementation](https://github.com/vectorize-io/hindsight/blob/1152717735237c26986b877789704b89bac89681/hindsight-api-slim/hindsight_api/engine/retain/fact_extraction.py) informed contextualization, attribution and temporal rules. The prompts use this project's own schema and wording. See `documentation/PROMPT_DESIGN.md`; this is not a Hindsight reproduction. No LongMemEval score is claimed.

## Measured evaluation

```json
{json.dumps(r['evaluation'],indent=2)}
```

Schema validity, semantic support, reference coverage and live graph completion are separate measurements. Teacher-generated labels and same-family automated judging are correlated; they do not replace independent human evaluation. Historical iterations and failures are preserved in the executed notebook.

## Ollama

Download the GGUF, `Modelfile`, `inference/`, and `src/` from this repository, preserving their paths:

```bash
ollama create mem-extractor -f Modelfile
python inference/run.py --model mem-extractor --prompt-file rendered-prompt.txt
```

`rendered-prompt.txt` must contain a fully rendered task prompt including its events/facts. `inference/prompt.py` provides the project renderer. The helper builds the dynamic JSON schema, invokes Ollama with thinking disabled, and converts paired source quotes to the canonical API shape. **Unconstrained casual chat is not the trained interface.** Exact-span restrictions establish textual attribution, not semantic entailment; the application must still validate outputs against supplied evidence.

## PEFT adapter

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
base = AutoModelForCausalLM.from_pretrained(
    "{BASE}", revision="{REVISION}", torch_dtype="auto", device_map="auto")
model = PeftModel.from_pretrained(base, "aryaniyaps/mem-extractor", subfolder="adapter")
tokenizer = AutoTokenizer.from_pretrained("{BASE}", revision="{REVISION}")
```

The adapter's base must match the pinned revision. A merged bf16 load requires substantially more memory than quantized serving. The notebook records the training token cap; a larger Ollama context setting does not establish long-context accuracy.

## Limitations

{chr(10).join('- '+str(x) for x in r['limitations'])}

The worker can still misattribute statements, mishandle time, over-extract transient details or infer unsupported relationships. Do not treat stored claims as verified truth or medical/legal advice. Keep source evidence and permit correction/deletion in the host application.

## Reproducibility and files

`release-receipt.json` contains aggregate counts, run configuration and evaluation. `SHA256SUMS` identifies every staged artifact except the checksum manifest itself. `documentation/Finetuning_Iteration_Report.ipynb` documents the actual assisted experiment and unsuccessful iterations. Raw private conversation data, caches, authentication files and optimizer states are excluded.
'''

if __name__=='__main__': main()
